In [3]:
import pandas as pd
import numpy as np
import scipy.stats
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("/content/boston_house_prices.csv")
print(df)

         506  13 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0       CRIM  ZN      INDUS       CHAS        NOX         RM        AGE   
1    0.00632  18       2.31          0      0.538      6.575       65.2   
2    0.02731   0       7.07          0      0.469      6.421       78.9   
3    0.02729   0       7.07          0      0.469      7.185       61.1   
4    0.03237   0       2.18          0      0.458      6.998       45.8   
..       ...  ..        ...        ...        ...        ...        ...   
502  0.06263   0      11.93          0      0.573      6.593       69.1   
503  0.04527   0      11.93          0      0.573       6.12       76.7   
504  0.06076   0      11.93          0      0.573      6.976         91   
505  0.10959   0      11.93          0      0.573      6.794       89.3   
506  0.04741   0      11.93          0      0.573       6.03       80.8   

    Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  \
0          DIS        R

In [5]:
df.head()

506  13 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0     CRIM  ZN      INDUS       CHAS        NOX         RM        AGE   
1  0.00632  18       2.31          0      0.538      6.575       65.2   
2  0.02731   0       7.07          0      0.469      6.421       78.9   
3  0.02729   0       7.07          0      0.469      7.185       61.1   
4  0.03237   0       2.18          0      0.458      6.998       45.8   

  Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  \
0        DIS        RAD        TAX     PTRATIO           B       LSTAT   
1       4.09          1        296        15.3       396.9        4.98   
2     4.9671          2        242        17.8       396.9        9.14   
3     4.9671          2        242        17.8      392.83        4.03   
4     6.0622          3        222        18.7      394.63        2.94   

  Unnamed: 13  
0        MEDV  
1          24  
2        21.6  
3        34.7  
4        33.4

In [6]:
df.describe()

506   13 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
count       507  507        507        507        507        507        507   
unique      505   27         77          3         82        447        357   
top     0.01501    0       18.1          0      0.538      6.417        100   
freq          2  372        132        471         23          3         43   

       Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  \
count         507        507        507         507         507         507   
unique        413         10         67          47         358         456   
top        3.4952         24        666        20.2       396.9        8.05   
freq            5        132        132         140         121           3   

       Unnamed: 13  
count          507  
unique         230  
top             50  
freq            16

In [7]:
df.isnull().sum()

506            0
13             0
Unnamed: 2     0
Unnamed: 3     0
Unnamed: 4     0
Unnamed: 5     0
Unnamed: 6     0
Unnamed: 7     0
Unnamed: 8     0
Unnamed: 9     0
Unnamed: 10    0
Unnamed: 11    0
Unnamed: 12    0
Unnamed: 13    0
dtype: int64

In [8]:
dt=df.iloc[3]
print(dt)

506            0.02729
13                   0
Unnamed: 2        7.07
Unnamed: 3           0
Unnamed: 4       0.469
Unnamed: 5       7.185
Unnamed: 6        61.1
Unnamed: 7      4.9671
Unnamed: 8           2
Unnamed: 9         242
Unnamed: 10       17.8
Unnamed: 11     392.83
Unnamed: 12       4.03
Unnamed: 13       34.7
Name: 3, dtype: object


In [9]:
df.sort_index(axis=1,ascending=False)

Unnamed: 9 Unnamed: 8 Unnamed: 7 Unnamed: 6 Unnamed: 5 Unnamed: 4  \
0          TAX        RAD        DIS        AGE         RM        NOX   
1          296          1       4.09       65.2      6.575      0.538   
2          242          2     4.9671       78.9      6.421      0.469   
3          242          2     4.9671       61.1      7.185      0.469   
4          222          3     6.0622       45.8      6.998      0.458   
..         ...        ...        ...        ...        ...        ...   
502        273          1     2.4786       69.1      6.593      0.573   
503        273          1     2.2875       76.7       6.12      0.573   
504        273          1     2.1675         91      6.976      0.573   
505        273          1     2.3889       89.3      6.794      0.573   
506        273          1      2.505       80.8       6.03      0.573   

    Unnamed: 3 Unnamed: 2 Unnamed: 13 Unnamed: 12 Unnamed: 11 Unnamed: 10  \
0         CHAS      INDUS        MEDV       LSTAT           B     PTRATIO   
1            0       2.31          24        4.98       396.9        15.3   
2            0       7.07        21.6        9.14       396.9        17.8   
3            0       7.07        34.7        4.03      392.83        17.8   
4            0       2.18        33.4        2.94      394.63        18.7   
..         ...        ...         ...         ...         ...         ...   
502          0      11.93        22.4        9.67      391.99          21   
503          0      11.93        20.6        9.08       396.9          21   
504          0      11.93        23.9        5.64       396.9          21   
505          0      11.93          22        6.48      393.45          21   
506          0      11.93        11.9        7.88       396.9          21   

         506  13  
0       CRIM  ZN  
1    0.00632  18  
2    0.02731   0  
3    0.02729   0  
4    0.03237   0  
..       ...  ..  
502  0.06263   0  
503  0.04527   0  
504  0.06076   0  
505  0.10959   0  
506  0.04741   0  

[507 rows x 14 columns]

In [10]:
print(df.iloc[2:4,3:5])

  Unnamed: 3 Unnamed: 4
2          0      0.469
3          0      0.469


In [11]:
print(df.iloc[:,3:5])

    Unnamed: 3 Unnamed: 4
0         CHAS        NOX
1            0      0.538
2            0      0.469
3            0      0.469
4            0      0.458
..         ...        ...
502          0      0.573
503          0      0.573
504          0      0.573
505          0      0.573
506          0      0.573

[507 rows x 2 columns]


In [12]:
dt=df.stack(future_stack=True)
print(dt)

0    506             CRIM
     13                ZN
     Unnamed: 2     INDUS
     Unnamed: 3      CHAS
     Unnamed: 4       NOX
                    ...  
506  Unnamed: 9       273
     Unnamed: 10       21
     Unnamed: 11    396.9
     Unnamed: 12     7.88
     Unnamed: 13     11.9
Length: 7098, dtype: object


In [16]:
df=np.arange(10,15)
df1=np.array([11,12,13,14,15])
print(df)
print(df1)
np.corrcoef(df,df1)

[10 11 12 13 14]
[11 12 13 14 15]


array([[1., 1.],
       [1., 1.]])

In [17]:
df=np.arange(25,30)
df1=np.array([11,15,23,25,29])
r=np.corrcoef(df,df1)
r1=scipy.stats.pearsonr(df,df1)
print(r1[0],r1[1])
r2=scipy.stats.spearmanr(df,df1)
print(r2[0],r2[1])
r3=scipy.stats.kendalltau(df,df1)
print([r3[0],r3[1]])

0.9825113063742752 0.0027690279453106
0.9999999999999999 1.4042654220543672e-24
[0.9999999999999999, 0.016666666666666666]


In [18]:
df=np.arange(25,30)
df1=np.array([11,15,23,25,29])
r=np.corrcoef(df,df1)
r1,p1=scipy.stats.pearsonr(df,df1)
print(r1,p1)
r2,p2=scipy.stats.spearmanr(df,df1)
print(r2,p2)
r3,p3=scipy.stats.kendalltau(df,df1)
print(r3,p3)

0.9825113063742752 0.0027690279453106
0.9999999999999999 1.4042654220543672e-24
0.9999999999999999 0.016666666666666666


In [19]:
reg=scipy.stats.linregress(df,df1)
print(reg)
print(reg.slope)
print(reg.rvalue)
print(reg.pvalue)
print(reg.stderr)
print(reg.intercept)
print(reg.intercept_stderr)

LinregressResult(slope=4.6000000000000005, intercept=-103.60000000000002, rvalue=0.9825113063742752, pvalue=0.002769027945310598, stderr=0.503322295684715, intercept_stderr=13.608330781791919)
4.6000000000000005
0.9825113063742752
0.002769027945310598
0.503322295684715
-103.60000000000002
13.608330781791919
